// packages/solid/src/index.ts
/// <reference lib="dom" />
/** SolidJS adapters. Import from 'scopekit/solid'; requires solid-js >= 1.7. */
import { createEffect, createSignal, onCleanup, type Accessor } from 'solid-js';
import { Scope, type ScopeOptions } from '@scopekit/core/scope';
import { latest } from '@scopekit/core/latest';
import { isAbort } from '@scopekit/core/signal';
import { on, type OnOptions } from '@scopekit/core/events';
import { wrap, type Remote } from '@scopekit/core/worker';

/** A scope that closes when the owning reactive root is disposed. */
export function createScope(opts?: ScopeOptions): Scope {
  const scope = new Scope(opts);
  onCleanup(() => {
    void scope.close();
  });
  return scope;
}

/**
 * createEffect with a Scope. Signals read in the synchronous part of `effect` are tracked;
 * each re-run closes the previous scope.
 */
export function scopedEffect(effect: (scope: Scope) => void | Promise<void>, opts?: ScopeOptions): void {
  createEffect(() => {
    const scope = new Scope(opts);
    onCleanup(() => {
      void scope.close();
    });
    void scope.spawn((_sig, s) => Promise.resolve(effect(s)), { name: 'effect' });
  });
}

export interface CreateAsync<T> {
  data: Accessor<T | null>;
  error: Accessor<unknown>;
  loading: Accessor<boolean>;
}

/** Loads data in a scoped effect. Results of a cancelled run never reach the signals. */
export function createAsync<T>(fn: (scope: Scope) => Promise<T>, opts?: ScopeOptions): CreateAsync<T> {
  const [data, setData] = createSignal<T | null>(null);
  const [error, setError] = createSignal<unknown>(null);
  const [loading, setLoading] = createSignal(false);
  scopedEffect(async scope => {
    setLoading(true);
    setError(null);
    try {
      const value = await fn(scope);
      if (!scope.signal.aborted) {
        setData(() => value);
        setLoading(false);
      }
    } catch (err) {
      if (!isAbort(err)) {
        setError(() => err);
        setLoading(false);
      }
    }
  }, opts);
  return { data, error, loading };
}

export interface CreateLatest<A, R> {
  run: (arg: A, signal?: AbortSignal) => Promise<R>;
  pending: Accessor<boolean>;
  cancel: () => void;
}

/** latest() bound to the reactive root: disposal cancels the in-flight call. */
export function createLatest<A, R>(fn: (arg: A, signal: AbortSignal) => Promise<R>): CreateLatest<A, R> {
  const wrapped = latest(fn);
  const [pending, setPending] = createSignal(false);
  onCleanup(() => wrapped.cancel());
  const run = async (arg: A, signal?: AbortSignal) => {
    setPending(true);
    try {
      return await wrapped(arg, signal);
    } finally {
      if (!wrapped.pending) setPending(false);
    }
  };
  const cancel = () => {
    wrapped.cancel();
    setPending(false);
  };
  return { run, pending, cancel };
}

/** Consumes DOM events in a scoped loop for the lifetime of the reactive root. */
export function createEventStream<E extends Event = Event>(
  target: EventTarget,
  type: string,
  handler: (event: E, scope: Scope) => void | Promise<void>,
  opts?: Omit<OnOptions, 'signal'>,
): void {
  const scope = createScope({ name: `on:${type}` });
  void scope.spawn(async (sig, s) => {
    for await (const e of on<E>(target, type, { ...opts, signal: sig })) await handler(e, s);
  });
}

/** Creates the worker, wraps it, terminates it on disposal. */
export function createWorker<T>(factory: () => Worker): Remote<T> {
  const worker = factory();
  const api = wrap<T>(worker);
  onCleanup(() => {
    api[Symbol.dispose]();
    worker.terminate();
  });
  return api;
}

// packages/angular/src/index.ts
/// <reference lib="dom" />
/** Angular adapters. Import from 'scopekit/angular'; requires @angular/core >= 17 (signals, DestroyRef). */
import { DestroyRef, effect, inject, signal, type Signal } from '@angular/core';
import { Scope, type ScopeOptions } from '@scopekit/core/scope';
import { latest } from '@scopekit/core/latest';
import { isAbort } from '@scopekit/core/signal';
import { on, type OnOptions } from '@scopekit/core/events';
import { wrap, type Remote } from '@scopekit/core/worker';

/** A scope that closes when the current injection context is destroyed. Call in a constructor or field initializer. */
export function injectScope(opts?: ScopeOptions): Scope {
  const scope = new Scope(opts);
  inject(DestroyRef).onDestroy(() => {
    void scope.close();
  });
  return scope;
}

/**
 * Angular effect() with a Scope. Signals read in the synchronous part of `fn` are tracked;
 * each re-run closes the previous scope.
 */
export function scopedEffect(fn: (scope: Scope) => void | Promise<void>, opts?: ScopeOptions): void {
  effect(onCleanup => {
    const scope = new Scope(opts);
    onCleanup(() => {
      void scope.close();
    });
    void scope.spawn((_sig, s) => Promise.resolve(fn(s)), { name: 'effect' });
  });
}

export interface InjectAsync<T> {
  data: Signal<T | null>;
  error: Signal<unknown>;
  loading: Signal<boolean>;
}

/** Loads data in a scoped effect. Results of a cancelled run never reach the signals. */
export function injectAsync<T>(fn: (scope: Scope) => Promise<T>, opts?: ScopeOptions): InjectAsync<T> {
  const data = signal<T | null>(null);
  const error = signal<unknown>(null);
  const loading = signal(false);
  scopedEffect(async scope => {
    loading.set(true);
    error.set(null);
    try {
      const value = await fn(scope);
      if (!scope.signal.aborted) {
        data.set(value);
        loading.set(false);
      }
    } catch (err) {
      if (!isAbort(err)) {
        error.set(err);
        loading.set(false);
      }
    }
  }, opts);
  return { data: data.asReadonly(), error: error.asReadonly(), loading: loading.asReadonly() };
}

export interface InjectLatest<A, R> {
  run: (arg: A, signal?: AbortSignal) => Promise<R>;
  pending: Signal<boolean>;
  cancel: () => void;
}

/** latest() bound to the injection context: destruction cancels the in-flight call. */
export function injectLatest<A, R>(fn: (arg: A, signal: AbortSignal) => Promise<R>): InjectLatest<A, R> {
  const wrapped = latest(fn);
  const pending = signal(false);
  inject(DestroyRef).onDestroy(() => wrapped.cancel());
  const run = async (arg: A, sig?: AbortSignal) => {
    pending.set(true);
    try {
      return await wrapped(arg, sig);
    } finally {
      if (!wrapped.pending) pending.set(false);
    }
  };
  const cancel = () => {
    wrapped.cancel();
    pending.set(false);
  };
  return { run, pending: pending.asReadonly(), cancel };
}

/** Consumes DOM events in a scoped loop for the lifetime of the injection context. */
export function injectEventStream<E extends Event = Event>(
  target: EventTarget,
  type: string,
  handler: (event: E, scope: Scope) => void | Promise<void>,
  opts?: Omit<OnOptions, 'signal'>,
): void {
  const scope = injectScope({ name: `on:${type}` });
  void scope.spawn(async (sig, s) => {
    for await (const e of on<E>(target, type, { ...opts, signal: sig })) await handler(e, s);
  });
}

/** Creates the worker, wraps it, terminates it on destroy. */
export function injectWorker<T>(factory: () => Worker): Remote<T> {
  const worker = factory();
  const api = wrap<T>(worker);
  inject(DestroyRef).onDestroy(() => {
    api[Symbol.dispose]();
    worker.terminate();
  });
  return api;
}
